@echo off
REM ****************************************************************************
REM Vivado (TM) v2023.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Aug 06 10:36:59 +0200 2025
REM SW Build 3865809 on Sun May  7 15:05:29 MDT 2023
REM
REM IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim pipeline_tb_func_synth -key {Post-Synthesis:sim_1:Functional:pipeline_tb} -tclbatch pipeline_tb.tcl -view D:/Programming/TESI/MFCC_Blocks/fft_tb_behav.wcfg -view D:/Programming/TESI/MFCC_Blocks/filterbank_tb_behav.wcfg -view D:/Programming/TESI/MFCC_Blocks/spectrum_bank_tb_behav.wcfg -view D:/Programming/TESI/MFCC_Blocks/log_tb_behav.wcfg -view D:/Programming/TESI/MFCC_Blocks/dct_tb_behav.wcfg -view D:/Programming/TESI/MFCC_Blocks/sin_lift_tb_behav.wcfg -view D:/Programming/TESI/MFCC_Blocks/preemph_tb_behav.wcfg -view D:/Programming/TESI/MFCC_Blocks/frame_tb_behav.wcfg -view D:/Programming/TESI/MFCC_Blocks/window_tb_behav.wcfg -view D:/Programming/TESI/MFCC_Blocks/spectrum_tb_behav.wcfg -view D:/Programming/TESI/MFCC_Blocks/design_tb_behav.wcfg -view D:/Programming/TESI/MFCC_Blocks/pipeline_tb_behav.wcfg -log simulate.log"
call xsim  pipeline_tb_func_synth -key {Post-Synthesis:sim_1:Functional:pipeline_tb} -tclbatch pipeline_tb.tcl -view D:/Programming/TESI/MFCC_Blocks/fft_tb_behav.wcfg -view D:/Programming/TESI/MFCC_Blocks/filterbank_tb_behav.wcfg -view D:/Programming/TESI/MFCC_Blocks/spectrum_bank_tb_behav.wcfg -view D:/Programming/TESI/MFCC_Blocks/log_tb_behav.wcfg -view D:/Programming/TESI/MFCC_Blocks/dct_tb_behav.wcfg -view D:/Programming/TESI/MFCC_Blocks/sin_lift_tb_behav.wcfg -view D:/Programming/TESI/MFCC_Blocks/preemph_tb_behav.wcfg -view D:/Programming/TESI/MFCC_Blocks/frame_tb_behav.wcfg -view D:/Programming/TESI/MFCC_Blocks/window_tb_behav.wcfg -view D:/Programming/TESI/MFCC_Blocks/spectrum_tb_behav.wcfg -view D:/Programming/TESI/MFCC_Blocks/design_tb_behav.wcfg -view D:/Programming/TESI/MFCC_Blocks/pipeline_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
