@echo off
REM ****************************************************************************
REM Vivado (TM) v2023.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Jul 28 13:31:43 +0200 2025
REM SW Build 3865809 on Sun May  7 15:05:29 MDT 2023
REM
REM IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim spectrum_bank_tb_behav -key {Behavioral:sim_1:Functional:spectrum_bank_tb} -tclbatch spectrum_bank_tb.tcl -view D:/Programming/TESI/MFCC_Blocks/fft_tb_behav.wcfg -view D:/Programming/TESI/MFCC_Blocks/filterbank_tb_behav.wcfg -view D:/Programming/TESI/MFCC_Blocks/spectrum_bank_tb_behav.wcfg -view D:/Programming/TESI/MFCC_Blocks/log_tb_behav.wcfg -log simulate.log"
call xsim  spectrum_bank_tb_behav -key {Behavioral:sim_1:Functional:spectrum_bank_tb} -tclbatch spectrum_bank_tb.tcl -view D:/Programming/TESI/MFCC_Blocks/fft_tb_behav.wcfg -view D:/Programming/TESI/MFCC_Blocks/filterbank_tb_behav.wcfg -view D:/Programming/TESI/MFCC_Blocks/spectrum_bank_tb_behav.wcfg -view D:/Programming/TESI/MFCC_Blocks/log_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
